version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_PORT:$MYSQLDB_PORT
    volumes:
      - db:/var/lib/mysql
      - ./myapp/db/mysmarthomeStructureAndData.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  app:
    depends_on:
      - mysqldb
      # - mongo
    build: ./myapp
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $API_PORT:$API_PORT
    environment:
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
      - MYSQLDB_PORT=$MYSQLDB_PORT
      - MYSQLDB_HOST=mysqldb
    stdin_open: true
    tty: true
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: $MYSQLDB_PORT
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 8081:80
  
  client:
    depends_on:
      - app
    build: ./client
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mysqldb
      - REACT_APP_SUBSCRIPTION_URL=$REACT_APP_SUBSCRIPTION_URL
      - REACT_APP_PUBLIC_VAPID_KEY=$REACT_APP_PUBLIC_VAPID_KEY
      - SKIP_PREFLIGHT_CHECK=$SKIP_PREFLIGHT_CHECK
      - REACT_APP_API_URL=$REACT_APP_API_URL
      - NODE_ENV=test
      - REACT_APP_API_PORT=$REACT_APP_API_PORT
    stdin_open: true
    tty: true

  camera_app:
    depends_on:
      - app
      - client
      # - mongo
    build: ./securityCamera
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $CAMERA_API_PORT:$CAMERA_API_PORT
    environment:
      - PUBLIC_VAPID_KEY=$PUBLIC_VAPID_KEY
      - PRIVATE_VAPID_KEY=$PRIVATE_VAPID_KEY
      - WEB_PUSH_CONTACT=$WEB_PUSH_CONTACT
      - CAMERA_API=$CAMERA_API
      - CAMERA_API_PORT=$CAMERA_API_PORT
      - APP_PORT=$APP_PORT
      - APP_API=http://app
      - from=$from
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
    stdin_open: true
    tty: true

volumes: 
  db: