version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_PORT:$MYSQLDB_PORT
    volumes:
      - db:/var/lib/mysql
      - ./myapp/db/mysmarthomeStructureAndData.sql:/docker-entrypoint-initdb.d/schema.sql:ro
  # mongo:
  #   image: mongo
  #   ports:
  #     - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
  #   volumes:
  #     - mongodb:/data/db
  app:
    depends_on:
      - mysqldb
      # - mongo
    build: ./myapp
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $API_PORT:$API_PORT
    environment:
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
      - MYSQLDB_PORT=$MYSQLDB_PORT
      - MYSQLDB_HOST=$MYSQLDB_HOST
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - MONGODB_PORT=$MONGODB_PORT
    stdin_open: true
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: $MYSQLDB_PORT
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 8081:80
  client:
    depends_on:
      - app
    build: ./client
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mysqldb
      - REACT_APP_API_URL=$REACT_APP_API_URL
      - REACT_APP_PUBLIC_VAPID_KEY=$REACT_APP_PUBLIC_VAPID_KEY
      - SKIP_PREFLIGHT_CHECK=$SKIP_PREFLIGHT_CHECK
      - API_URL=$API_URL
      - NODE_ENV=test
      - API_PORT=$API_PORT
    stdin_open: true
    tty: true

volumes: 
  db:
  # mongodb: